language: python
python:
    - "3.5"
before_script:
    - pip install coverage && pip install python-coveralls
install: "pip install git+git://github.com/bnbalsamo/pyqremis.git && pip install ."
services:
    - redis
script: coverage run --source qremis_spiderlib tests.py
after_success:
    - coveralls
